### ISSUE TITLE
Time field in output FCDR is zero

### ISSUE THREAD

**Issue by jmittaz** [FIDUCEO/FCDR_HIRS#382]
For some files (maybe all) under v0.8pre2 and v0.8pre2_no_harm which are being used for matchup generation as well as HIRS CDR and C3S/NCEO aerosol  work the time field can be filled with zeros. This is a blocking problem

**Comment by gerritholl** [comment]
This is the same as #370 and was fixed in #372 but the bug was present when those versions were generated, should not be present for any files generated after this.

**Comment by jmittaz** [comment]
Thank you Gerrit – I must have a slightly older than that version so I’ll update and see if it goes away.

Dept. of Meteorology, University of Reading
Room 3L64, Department of Meteorology, Earley Gate, PO Box 243
Whiteknights, Reading, RG6 6BB
tel: +44 (0)118 378 6732

**Comment by jmittaz** [comment]
Update of code fixed issue
