### ISSUE TITLE
Investigate why nc_browse software fails to read HIRS easy_FCDR files

### ISSUE THREAD

**Issue by gerritholl** [FIDUCEO/FCDR_HIRS#92]
Frank reports he cannot read the HIRS FCDR easy files with his software.  Need to find out why.

**Comment by frarue** [comment]
the software that cannot decode the x and channel dimensions (and thus not display the data) is NOAA's ncBrowse. http://www.epic.noaa.gov/java/ncBrowse/

**Comment by gerritholl** [comment]
When rewriting the coordinates from UBYTE to USHORT ncBrowse is able to graph.  BYTE and UBYTE are valid NetCDF types.  Therefore, this is a bug in ncBrowse and not in my data files.
